### ISSUE TITLE
Hard Coded client_id

### ISSUE THREAD

**Issue by divThis** [XanderStrike/goplaxt#1]
The file `static/index.html` currently has your `client_id` hard coded instead of using the one set via the `TRAKT_ID` env variable which causes this error from Trakt when authorizing from the front-end.

> The requested redirect uri is malformed or doesn't match client redirect URI.

**Comment by vistalba** [comment]
I'm little confused but I think I ran into the same issue..
I run the docker container directly in my kubernetes cluster. 

I'm not sure what to put in the "Redirect URI" on trakt and ENV for the docker?! Any hint?

Anyway... if I visit my https://plaxturl, put my username in it and click "Authorize" it opens trakt but with another client ID?!

And there is also one last question:
What to put in as "id=generate-your-own-silly" ... the client_id from trakt app?

**Comment by bassrock** [comment]
Looks like this line needs to be templated and pull in the client id from environment variables. https://github.com/XanderStrike/goplaxt/blob/master/static/index.html#L108

**Comment by XanderStrike** [comment]
Wow, that's bad. Thanks for pointing this out y'all. I'll push a fix in a sec.
