### ISSUE TITLE
Oh no!

### ISSUE THREAD

**Issue by ryaniskira** [XanderStrike/goplaxt#16]
As of yesterday's update, all that I see when I navigate to Plaxt is "Oh no!" and even after removing the container and starting from scratch this error continues.

**Comment by XanderStrike** [comment]
Oh no! There was a minor change in how the application needs to be configured, namely using `ALLOWED_HOSTNAME=` instead of `REDIRECT_URI` that might be causing this. It should be backwards compatible though (at least it was in my testing). Try configuring that and let me know how it goes.

**Comment by ryaniskira** [comment]
That does work. I do have a question though. I have everything behind an Nginx reverse proxy via Cloudflare and while I can navigate to Plaxt through it, authorizing doesn't seem to work. Do you have any experience with using Plaxt through this type of setup?

**Comment by XanderStrike** [comment]
I run plaxt behind an nginx proxy but I use the [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy) rather than something from an external provider like Cloudflare. That all seems to work fine though so I can't guess why it's not working there. I'm glad it's working through a local IP address though.

**Comment by jeffchen86** [comment]
> Oh no! There was a minor change in how the application needs to be configured, namely using `ALLOWED_HOSTNAME=` instead of `REDIRECT_URI` that might be causing this. It should be backwards compatible though (at least it was in my testing). Try configuring that and let me know how it goes.

REDIRECT_URI doesn't work for me. Still getting the 'Oh no!'. :(
