### ISSUE TITLE
Update docker image automatically

### ISSUE THREAD

**Issue by halkeye** [XanderStrike/goplaxt#18]
Is the image deployed manually? or automatically somewhere?

the official one doesn't seem to have my healthcheck fixes in it so i'm getting 401s

**Comment by XanderStrike** [comment]
So sorry! I do it manually and I forgot to `docker push` 😐 

I keep meaning to get a concourse pipeline up to do it automagically.

**Comment by halkeye** [comment]
No worries, just took me a few minutes when i switched back to the official url.

I don't know anything about circle, but I do know its pretty easy to add docker push to travis (and since I work for a competator i shouldn't say much else). I'm sure they are pretty much all the same.

I could help convert the docker image into multi stage so it can be done directly on dockerhub (example - https://github.com/vouch/vouch-proxy/blob/master/Dockerfile)
