### ISSUE TITLE
Does this have to be accessible externally?

### ISSUE THREAD

**Issue by yegle** [XanderStrike/goplaxt#20]
The HTTP request for the webhook is originated from the Plex server. If you run your plex server in docker and within the same docker network, you don't need to expose plaxt to public at all.

Does that make sense to you? The README may need some update.

**Comment by XanderStrike** [comment]
You're totally right.

I put that because I personally play media from a bunch of different servers that all live on different networks, so making it accessible to the public internet was a requirement.
