### ISSUE TITLE
Tracking viewing for multiple users

### ISSUE THREAD

**Issue by rashuge** [XanderStrike/goplaxt#22]
I have a single Plex account but I have multiple accounts under my Plex install.  With the webhook in place, it only works with Trakt to show the things that my main account has watched.  It does not show my subaccounts.

**Comment by XanderStrike** [comment]
That's the expected behavior! 

Both Trakt accounts and Home Users are meant to map to a single human being. If you'd like multiple Home Users to map to a single Trakt account, you can make additional webhook urls for each Home User.

**Comment by patrick1227** [comment]
i know this is closed. i would like to know how would i login to one of the other home users with this. in otherwords. what would i use as the plex username for a secondary account
