### ISSUE TITLE
[Feature] Mark as watched in Plex

### ISSUE THREAD

**Issue by Inrego** [XanderStrike/goplaxt#28]
It would be really nice with an addition to sync the other way as well - to update watched status in Plex from Trakt. I hope you will consider it.

**Comment by XanderStrike** [comment]
This will never be possible with webhooks.

**Comment by Inrego** [comment]
No, not webhooks. But it's possible by calling the API. I agree there's still the issue of when to run that batch, since there's not a logical web hook. It could be manual by visiting an url on your backend to trigger it, or an api call. I think many people would be fine with being able to manually trigger it, or set up a scheduled task.

With plugins phasing out, I know many people are looking for a solution to this. Especially people who are using an NVIDIA Shield as server, as the Trakt plugin doesn't work there without rooting.

**Comment by Inrego** [comment]
I developed my own solution for that, if anyone is interested. You can read more here: https://www.reddit.com/r/PleX/comments/cnnvxb/i_created_a_tool_to_sync_from_trakt_to_plex/
