### ISSUE TITLE
hello question

### ISSUE THREAD

**Issue by valantislevas** [XanderStrike/goplaxt#32]
Hello thanks for ur work.. i tried to setup my own server of plaxt i do the steps and i make trakt app with all the info.. how i can setup the website to make people type their username and get the link?

i saw the index.html on static folder but when i put my username and tried to authorize says " oops.. 

something i do wrong about setting the page.. i think trakt app and ip and setting is ok..

thanks..

**Comment by XanderStrike** [comment]
Follow the instructions for running in docker
