### ISSUE TITLE
only allowed 6 webhooks?!?

### ISSUE THREAD

**Issue by KennyVB** [XanderStrike/goplaxt#37]
hello, think i'm missing something,
gotr 26 users on my server, want them to all use trakt of there own, i have plex pass as server owner.
can only put in 6 webhooks?
i thougth i could write in all 26 users on each there own trakt log etc, useing my webhooks?!?

**Comment by halkeye** [comment]
I think webhooks are per user

**Comment by XanderStrike** [comment]
I haven't tested it, but it wouldn't surprise me if there are limits on how many webhooks Plex will send. This would be a great question for the Plex support forums since it doesn't sound like this is an issue with Plaxt.
