### ISSUE TITLE
Not all shows being Trakt

### ISSUE THREAD

**Issue by Tragyn** [XanderStrike/goplaxt#38]
Hi there,

I've set everything up properly, and all of my shows are showing on Trakt, but some of them are way behind on watch status.  For example, with "Arrow", I'm on S4E08, but Trakt shows me at S1E1 (and no episodes after are watch either).

Any ideas what I may have done wrong?

**Comment by sylvaindd** [comment]
Hello,

Seems like I have this problem as well.

**Plex logs** : Webhook: Error delivering payload to https://plaxt.DOMAIN/api?id=APIKEY: 502
**Plaxt logs** :
`2019/10/27 16:16:12 http: panic serving 172.19.0.23:50930: runtime error: index out of range
goroutine 133 [running]:
net/http.(*conn).serve.func1(0xc00042e820)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x85bf60, 0xcbdcc0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/xanderstrike/goplaxt/lib/trakt.findEpisode(0xc000572e20, 0xb, 0x101, 0x1, 0xc000567440, 0x3a, 0xc000572e30, 0x8, 0xc000572e58, 0x4, ...)
	/go/src/github.com/xanderstrike/goplaxt/lib/trakt/main.go:83 +0x755
github.com/xanderstrike/goplaxt/lib/trakt.HandleShow(0xc000572e20, 0xb, 0x101, 0x1, 0xc000567440, 0x3a, 0xc000572e30, 0x8, 0xc000572e58, 0x4, ...)
	/go/src/github.com/xanderstrike/goplaxt/lib/trakt/main.go:57 +0xfc
github.com/xanderstrike/goplaxt/lib/trakt.Handle(0xc000572e20, 0xb, 0x101, 0x1, 0xc000567440, 0x3a, 0xc000572e30, 0x8, 0xc000572e58, 0x4, ...)
	/go/src/github.com/xanderstrike/goplaxt/lib/trakt/main.go:45 +0x16b
main.api(0x9803a0, 0xc0004460e0, 0xc00046e500)
	/go/src/github.com/xanderstrike/goplaxt/main.go:104 +0x792
net/http.HandlerFunc.ServeHTTP(0x8fcb60, 0x9803a0, 0xc0004460e0, 0xc00046e500)
	/usr/local/go/src/net/http/server.go:1995 +0x44
main.allowedHostsHandler.func1.1(0x9803a0, 0xc0004460e0, 0xc00046e500)
	/go/src/github.com/xanderstrike/goplaxt/main.go:135 +0x2f3
net/http.HandlerFunc.ServeHTTP(0xc0002c5080, 0x9803a0, 0xc0004460e0, 0xc00046e500)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/gorilla/handlers.ProxyHeaders.func1(0x9803a0, 0xc0004460e0, 0xc00046e500)
	/go/pkg/mod/github.com/gorilla/handlers@v0.0.0-20190227193432-ac6d24f88de4/proxy_headers.go:59 +0x10d
net/http.HandlerFunc.ServeHTTP(0xc000503e60, 0x9803a0, 0xc0004460e0, 0xc00046e500)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000b80c0, 0x9803a0, 0xc0004460e0, 0xc00046e300)
	/go/pkg/mod/github.com/gorilla/mux@v0.0.0-20190228181203-15a353a63672/mux.go:212 +0xe3
net/http.serverHandler.ServeHTTP(0xc00008eea0, 0x9803a0, 0xc0004460e0, 0xc00046e300)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc00042e820, 0x980ea0, 0xc000166600)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4`

It crashes here :  goplaxt/lib/trakt/main.go:83
**log.Print(fmt.Sprintf("Finding show for %s %s %s", showID[1], showID[2], showID[3]))**

It works for some shows but doesn't for others, I had this problem with "Legacies S2 E3".

Anyone has any idea how to fix this ?

**Comment by XanderStrike** [comment]
Those ids are `show`, `season`, `episode`. If they're missing in the webhook there's no way we could positively identify what episode you're watching, so this is expected. Try refreshing metadata on plex?

**Comment by revelous** [comment]
I know this issue has been closed, but I have the same issue. I can open a new issue if that would be helpful. Some shows will track, others don't. For example, here's one:
`2020/01/27 22:51:42 Webhook call for 4bb372cca94f81d7a0be1acd653ce387
2020/01/27 22:51:42 http: panic serving 172.19.0.1:44608: runtime error: index out of range
goroutine 931 [running]:
net/http.(*conn).serve.func1(0xc00042e280)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x85bf60, 0xcbdcc0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/xanderstrike/goplaxt/lib/trakt.findEpisode(0xc0003acb80, 0xa, 0x101, 0x1, 0xc000088900, 0x3a, 0xc0003acb68, 0x7, 0xc0003acb98, 0x4, ...)
	/go/src/github.com/xanderstrike/goplaxt/lib/trakt/main.go:83 +0x755
github.com/xanderstrike/goplaxt/lib/trakt.HandleShow(0xc0003acb80, 0xa, 0x101, 0x1, 0xc000088900, 0x3a, 0xc0003acb68, 0x7, 0xc0003acb98, 0x4, ...)
	/go/src/github.com/xanderstrike/goplaxt/lib/trakt/main.go:57 +0xfc
github.com/xanderstrike/goplaxt/lib/trakt.Handle(0xc0003acb80, 0xa, 0x101, 0x1, 0xc000088900, 0x3a, 0xc0003acb68, 0x7, 0xc0003acb98, 0x4, ...)
	/go/src/github.com/xanderstrike/goplaxt/lib/trakt/main.go:45 +0x16b
main.api(0x9803a0, 0xc0003521c0, 0xc0000da700)
	/usr/local/go/src/net/http/server.go:1995 +0x44
main.allowedHostsHandler.func1.1(0x9803a0, 0xc0003521c0, 0xc0000da700)
	/go/src/github.com/xanderstrike/goplaxt/main.go:135 +0x2f3
net/http.HandlerFunc.ServeHTTP(0xc0002b0f90, 0x9803a0, 0xc0003521c0, 0xc0000da700)
	/usr/local/go/src/net/http/server.go:1995 +0x44
2020/01/27 22:51:51 Webhook call for 4bb372cca94f81d7a0be1acd653ce387
2020/01/27 22:51:51 http: panic serving 172.19.0.1:44848: runtime error: index out of range
goroutine 949 [running]:
`

I've tried refreshing the metadata in Plex. It doesn't seem to change anything.

**Comment by XanderStrike** [comment]
Alright now I'm curious, would you mind sharing the show name and episode that isn't scrobbling? The more examples you have the better.

**Comment by revelous** [comment]
I've noticed it on two series (all episodes) so far. Here are some examples:

Gentleman Jack S01E01
`2020/01/27 23:56:16 Webhook call for 4bb372cca94f81d7a0be1acd653ce387
2020/01/27 23:56:16 http: panic serving 172.19.0.1:34682: runtime error: index out of range
goroutine 1030 [running]:
net/http.(*conn).serve.func1(0xc000376c80)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/xanderstrike/goplaxt/lib/trakt.findEpisode(0xc00045e3b0, 0xa, 0x101, 0x1, 0xc000088d40, 0x3a, 0xc00045e398, 0x7, 0xc00045e3c8, 0x4, ...)
	/go/src/github.com/xanderstrike/goplaxt/lib/trakt/main.go:83 +0x755
github.com/xanderstrike/goplaxt/lib/trakt.HandleShow(0xc00045e3b0, 0xa, 0x101, 0x1, 0xc000088d40, 0x3a, 0xc00045e398, 0x7, 0xc00045e3c8, 0x4, ...)
	/go/src/github.com/xanderstrike/goplaxt/lib/trakt/main.go:57 +0xfc
github.com/xanderstrike/goplaxt/lib/trakt.Handle(0xc00045e3b0, 0xa, 0x101, 0x1, 0xc000088d40, 0x3a, 0xc00045e398, 0x7, 0xc00045e3c8, 0x4, ...)
	/go/src/github.com/xanderstrike/goplaxt/lib/trakt/main.go:45 +0x16b
main.api(0x9803a0, 0xc0003521c0, 0xc0000da600)
	/go/src/github.com/xanderstrike/goplaxt/main.go:104 +0x792
net/http.HandlerFunc.ServeHTTP(0x8fcb60, 0x9803a0, 0xc0003521c0, 0xc0000da600)
	/usr/local/go/src/net/http/server.go:1995 +0x44
main.allowedHostsHandler.func1.1(0x9803a0, 0xc0003521c0, 0xc0000da600)
	/go/src/github.com/xanderstrike/goplaxt/main.go:135 +0x2f3
net/http.HandlerFunc.ServeHTTP(0xc000069cb0, 0x9803a0, 0xc0003521c0, 0xc0000da600)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/gorilla/handlers.ProxyHeaders.func1(0x9803a0, 0xc0003521c0, 0xc0000da600)
	/go/pkg/mod/github.com/gorilla/handlers@v0.0.0-20190227193432-ac6d24f88de4/proxy_headers.go:59 +0x10d
net/http.HandlerFunc.ServeHTTP(0xc0003b81e0, 0x9803a0, 0xc0003521c0, 0xc0000da600)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000980c0, 0x9803a0, 0xc0003521c0, 0xc0000da400)
	/go/pkg/mod/github.com/gorilla/mux@v0.0.0-20190228181203-15a353a63672/mux.go:212 +0xe3
net/http.serverHandler.ServeHTTP(0xc000070c30, 0x9803a0, 0xc0003521c0, 0xc0000da400)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000376c80, 0x980ea0, 0xc00005aa40)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
`

The Outsider S01E01
`2020/01/27 23:57:48 Webhook call for 4bb372cca94f81d7a0be1acd653ce387
2020/01/27 23:57:48 http: panic serving 172.19.0.1:37116: runtime error: index out of range
goroutine 1006 [running]:
net/http.(*conn).serve.func1(0xc000082000)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x85bf60, 0xcbdcc0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/xanderstrike/goplaxt/lib/trakt.findEpisode(0xc0003ac140, 0xa, 0x101, 0x1, 0xc0002e6600, 0x3a, 0xc0003ac128, 0x7, 0xc0003ac158, 0x4, ...)
	/go/src/github.com/xanderstrike/goplaxt/lib/trakt/main.go:83 +0x755
github.com/xanderstrike/goplaxt/lib/trakt.HandleShow(0xc0003ac140, 0xa, 0x101, 0x1, 0xc0002e6600, 0x3a, 0xc0003ac128, 0x7, 0xc0003ac158, 0x4, ...)
	/go/src/github.com/xanderstrike/goplaxt/lib/trakt/main.go:57 +0xfc
github.com/xanderstrike/goplaxt/lib/trakt.Handle(0xc0003ac140, 0xa, 0x101, 0x1, 0xc0002e6600, 0x3a, 0xc0003ac128, 0x7, 0xc0003ac158, 0x4, ...)
	/go/src/github.com/xanderstrike/goplaxt/lib/trakt/main.go:45 +0x16b
main.api(0x9803a0, 0xc000430460, 0xc0002ba200)
	/go/src/github.com/xanderstrike/goplaxt/main.go:104 +0x792
net/http.HandlerFunc.ServeHTTP(0x8fcb60, 0x9803a0, 0xc000430460, 0xc0002ba200)
	/usr/local/go/src/net/http/server.go:1995 +0x44
main.allowedHostsHandler.func1.1(0x9803a0, 0xc000430460, 0xc0002ba200)
	/go/src/github.com/xanderstrike/goplaxt/main.go:135 +0x2f3
net/http.HandlerFunc.ServeHTTP(0xc0002b01e0, 0x9803a0, 0xc000430460, 0xc0002ba200)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/gorilla/handlers.ProxyHeaders.func1(0x9803a0, 0xc000430460, 0xc0002ba200)
	/go/pkg/mod/github.com/gorilla/handlers@v0.0.0-20190227193432-ac6d24f88de4/proxy_headers.go:59 +0x10d
net/http.HandlerFunc.ServeHTTP(0xc00036e020, 0x9803a0, 0xc000430460, 0xc0002ba200)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000980c0, 0x9803a0, 0xc000430460, 0xc0002ba000)
	/go/pkg/mod/github.com/gorilla/mux@v0.0.0-20190228181203-15a353a63672/mux.go:212 +0xe3
net/http.serverHandler.ServeHTTP(0xc000070c30, 0x9803a0, 0xc000430460, 0xc0002ba000)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000082000, 0x980ea0, 0xc00010c040)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
`

**Comment by XanderStrike** [comment]
Unfortunately I'm getting the same result. If I attempt to play the show immediately after downloading I can reproduce the issue, but that's because Plex doesn't know anything about the metadata, just the filename.

If I wait a bit until Plex has downloaded metadata for the episode, Plex sends a tvdb id with which Plaxt can positively identify it. I didn't do anything special with these episodes, just downloaded them and moved the files into the folders watched by Plex.

Does your episode have metadata that you did not add yourself, like poster, airdate, synopsis, director, etc? Do you have the TVDB agent turned on (this is the default)?

Unfortunately Plaxt is not in the business of identifying media titles by filename. Plex is already great at this problem and my previous attempts to solve it (I made a Plex competitor in college) were poor at best. Plaxt is only gonna be able to scrobble files that have already been identified by Plex unless I get a great PR from someone.

No metadata:
![Screen Shot 2020-01-27 at 4 36 49 PM](https://user-images.githubusercontent.com/1565303/73227022-f13b9d00-4126-11ea-8a31-69bb5ddace36.png)

With metadata:
![Screen Shot 2020-01-27 at 5 01 34 PM](https://user-images.githubusercontent.com/1565303/73227001-e1bc5400-4126-11ea-82ab-8d68b4473119.png)

Enabling TVDB Agent:
![Screen Shot 2020-01-27 at 5 07 17 PM](https://user-images.githubusercontent.com/1565303/73227185-82ab0f00-4127-11ea-9268-670c13c04b8f.png)

**Comment by revelous** [comment]
Ah, OK. I did have metadata but I think this is what must have happened: I had switched the metadata provider to The Movie Database when thetvdb was having all the API issues. I just now "unmatched" and then "matched" the shows again and now they're scrobbling. Thanks for the assistance.

**Comment by XanderStrike** [comment]
Fantastic! Glad that worked out.
