### ISSUE TITLE
Bad Gateway on Authorisation

### ISSUE THREAD

**Issue by JoeBoJoe** [XanderStrike/goplaxt#42]
Recently set plaxt up and it was working fine for a brief period but then stopped. Tried removing authentication and adding it again but now I am given a bad gateway on being re-directed back from trakt.tv

**Comment by montizzl3** [comment]
I'm having the same issue.

**Comment by jalarab** [comment]
same here

**Comment by taylh003** [comment]
Same here

**Comment by JamieCristofani** [comment]
Also seeing this issue.

**Comment by XanderStrike** [comment]
Is this the public instance or one you're hosting yourself?

https://plaxt.astandke.com/ is up, receiving traffic, and scrobbling correctly.

**Comment by taylh003** [comment]
> Is this the public instance or one you're hosting yourself?
> 
> https://plaxt.astandke.com/ is up, receiving traffic, and scrobbling correctly.

It was the public instance, but it seems to be all working now!

**Comment by montizzl3** [comment]
Looks like it's fixed. Thanks!

**Comment by XanderStrike** [comment]
Great! Glad to hear.

**Comment by terencepalmer** [comment]
Stopped working again.
