### ISSUE TITLE
Bad Gateway on Authorisation

### ISSUE THREAD

**Issue by terencepalmer** [XanderStrike/goplaxt#43]
This previously closed error has returned. Plex isn't scrobbling. The public Plaxt tool returns a "502 Bad Gateway" error.

**Comment by terencepalmer** [comment]
So this project is just broken now?

**Comment by XanderStrike** [comment]
It's working currently and I have not seen the error.

Feel free to host it yourself, or pay $30 a year and use Trakt's feature. Check your attitude, this is a free project.

**Comment by terencepalmer** [comment]
I was just asking a question. I appreciate the project and your work. It doesn't seem to work for me suddenly and you closed my issue with no comment.
