### ISSUE TITLE
Server crashes after authentication

### ISSUE THREAD

**Issue by arhammer77** [XanderStrike/goplaxt#48]
Here's my log files
`
2020/07/28 20:07:58 Handling auth request for ******** 

2020/07/28 20:07:58 Authorized as c2d86713296ba673eec252a2820fec43

2020/07/28 20:07:58 Got a 401 Unauthorized, full response:
&{401 Unauthorized 401 HTTP/2.0 2 0 map[Cache-Control:[no-store] Cf-Cache-Status:[DYNAMIC] Cf-Railgun:[7aebe2b78d 1.87 0.006365 0030 57da] Cf-Ray:[5ba13abf0f3e6bc6-SJC] Cf-Request-Id:[0438a30b6400006bc667b7e200000001] Content-Length:[213] Content-Type:[application/json; charset=utf-8] Date:[Tue, 28 Jul 2020 20:07:58 GMT] Expect-Ct:[max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"] Pragma:[no-cache] Server:[cloudflare] Set-Cookie:[__cfduid=de35f7dcf30671ee6f3a4b3f8529c85da1595966878; expires=Thu, 27-Aug-20 20:07:58 GMT; path=/; domain=.trakt.tv; HttpOnly; SameSite=Lax _traktsession=bEF3TisxQTh0UGlZSGtXSWtqZlFDV1dtM0poLzBNZTAvV0x1c3pZNDZaSGVOL29XL2tDeU9IN1pia1RxS1NQUWl2Q0ZaU21NSnZyL1MzT0k3d3h4NlE9PS0tUzBxVytyU3VtTk5WSTI2cWlrKy9ZUT09--e08bd785a5fd764367b42ee653ae0267bbfd010e; path=/; HttpOnly] Vary:[Accept-Encoding] Www-Authenticate:[Bearer realm="Doorkeeper", error="invalid_grant", error_description="The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."] X-Content-Type-Options:[nosniff] X-Frame-Options:[SAMEORIGIN] X-Request-Id:[3b3f9706-5365-43d3-bf80-6fffa93dc515] X-Runtime:[0.003935] X-Xss-Protection:[1; mode=block]] {0xc00022a8c0} 213 [] false false map[] 0xc000154c00 0xc0000a6370}. 
Aborting to avoid panic.

2020/07/28 20:07:58 http: panic serving 172.18.0.1:37574: interface conversion: interface {} is nil, not string
goroutine 66 [running]:
net/http.(*conn).serve.func1(0xc000194820)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x85fb40, 0xc00040d2f0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
main.authorize(0x9803e0, 0xc0001a4380, 0xc000154b00)
	/go/src/github.com/xanderstrike/goplaxt/main.go:57 +0x833
net/http.HandlerFunc.ServeHTTP(0x8fcb80, 0x9803e0, 0xc0001a4380, 0xc000154b00)
	/usr/local/go/src/net/http/server.go:1995 +0x44
main.allowedHostsHandler.func1.1(0x9803e0, 0xc0001a4380, 0xc000154b00)
	/go/src/github.com/xanderstrike/goplaxt/main.go:135 +0x2f3
net/http.HandlerFunc.ServeHTTP(0xc00040c0f0, 0x9803e0, 0xc0001a4380, 0xc000154b00)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/gorilla/handlers.ProxyHeaders.func1(0x9803e0, 0xc0001a4380, 0xc000154b00)
	/go/pkg/mod/github.com/gorilla/handlers@v0.0.0-20190227193432-ac6d24f88de4/proxy_headers.go:59 +0x10d
net/http.HandlerFunc.ServeHTTP(0xc0001ac900, 0x9803e0, 0xc0001a4380, 0xc000154b00)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000960c0, 0x9803e0, 0xc0001a4380, 0xc000154900)
	/go/pkg/mod/github.com/gorilla/mux@v0.0.0-20190228181203-15a353a63672/mux.go:212 +0xe3
net/http.serverHandler.ServeHTTP(0xc000070b60, 0x9803e0, 0xc0001a4380, 0xc000154900)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000194820, 0x980ee0, 0xc000348700)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4

2020/07/28 20:07:58 Handling auth request for ******

2020/07/28 20:07:59 Got a 401 Unauthorized, full response:
&{401 Unauthorized 401 HTTP/2.0 2 0 map[Cache-Control:[no-store] Cf-Cache-Status:[DYNAMIC] Cf-Railgun:[a71e967b66 99.99 0.007691 0030 57da] Cf-Ray:[5ba13ac138366bc6-SJC] Cf-Request-Id:[0438a30cc600006bc667b8c200000001] Content-Length:[213] Content-Type:[application/json; charset=utf-8] Date:[Tue, 28 Jul 2020 20:07:59 GMT] Expect-Ct:[max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"] Pragma:[no-cache] Server:[cloudflare] Set-Cookie:[__cfduid=de35f7dcf30671ee6f3a4b3f8529c85da1595966878; expires=Thu, 27-Aug-20 20:07:58 GMT; path=/; domain=.trakt.tv; HttpOnly; SameSite=Lax _traktsession=TTBTSStjNStCdE1XNkJLUEd2WG5ISnVyZ3pVWi9KclBaMXRmeHlhSjduT0hZa056M29IU3dybmEwRWdlWXhhZUFLRWF6aWRsa1orZGR6aDdzTERtYWc9PS0tVjlxUUNlYkZURGF6ems5MXRCblhZUT09--3badae8bc2a5bcd61211142627fb8cc59521a07e; path=/; HttpOnly] Vary:[Accept-Encoding] Www-Authenticate:[Bearer realm="Doorkeeper", error="invalid_grant", error_description="The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."] X-Content-Type-Options:[nosniff] X-Frame-Options:[SAMEORIGIN] X-Request-Id:[7996aa14-333b-4613-827a-056de5892918] X-Runtime:[0.003729] X-Xss-Protection:[1; mode=block]] {0xc00024a280} 213 [] false false map[] 0xc0001aea00 0xc0000a6370}. Aborting to avoid panic.

2020/07/28 20:07:59 http: panic serving 172.18.0.1:37576: interface conversion: interface {} is nil, not string
goroutine 44 [running]:
net/http.(*conn).serve.func1(0xc000080e60)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x85fb40, 0xc0003da570)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
main.authorize(0x9803e0, 0xc00010a0e0, 0xc0001ae900)
	/go/src/github.com/xanderstrike/goplaxt/main.go:57 +0x833
net/http.HandlerFunc.ServeHTTP(0x8fcb80, 0x9803e0, 0xc00010a0e0, 0xc0001ae900)
	/usr/local/go/src/net/http/server.go:1995 +0x44
main.allowedHostsHandler.func1.1(0x9803e0, 0xc00010a0e0, 0xc0001ae900)
	/go/src/github.com/xanderstrike/goplaxt/main.go:135 +0x2f3
net/http.HandlerFunc.ServeHTTP(0xc000130c60, 0x9803e0, 0xc00010a0e0, 0xc0001ae900)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/gorilla/handlers.ProxyHeaders.func1(0x9803e0, 0xc00010a0e0, 0xc0001ae900)
	/go/pkg/mod/github.com/gorilla/handlers@v0.0.0-20190227193432-ac6d24f88de4/proxy_headers.go:59 +0x10d
net/http.HandlerFunc.ServeHTTP(0xc0004823e0, 0x9803e0, 0xc00010a0e0, 0xc0001ae900)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000960c0, 0x9803e0, 0xc00010a0e0, 0xc0001ae700)
	/go/pkg/mod/github.com/gorilla/mux@v0.0.0-20190228181203-15a353a63672/mux.go:212 +0xe3
net/http.serverHandler.ServeHTTP(0xc000070b60, 0x9803e0, 0xc00010a0e0, 0xc0001ae700)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000080e60, 0x980ee0, 0xc00011e340)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4`

**Comment by XanderStrike** [comment]
I see this message in the logs:

> The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client

Please double-check the redirect URIs in Trakt are right according to the instructions in the readme. Feel free to reopen if it's still an issue.
