### ISSUE TITLE
Not scrobbling

### ISSUE THREAD

**Issue by EnorMOZ** [XanderStrike/goplaxt#5]
Just tried to set this up and it seems to be running. I am able to authenticate without issue. However I am not seeing any scrobbling occurring. How often does the webhook gets triggered ? In the logs i just see it up to the `Authorized as` message but then nothing else. Any plex logs I can look at ?

**Comment by EnorMOZ** [comment]
The following is in the goplaxt docker logs
```
2018/12/19 14:17:58 Handling auth request for enormoz
2018/12/19 14:17:58 Authorized as XXXXXXXXXXX
```
In the reverse proxy
```
nginx.1    | goplaxt.domain 1.1.1.1 - - [19/Dec/2018:14:17:51 -0500] "GET / HTTP/2.0" 200 3771 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
nginx.1    | goplaxt.domain 1.1.1.1 - - [19/Dec/2018:14:17:58 -0500] "GET /authorize?username=enormoz&code=XXXXXXXXXX HTTP/2.0" 200 3552 "https://goplaxt.domain/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
```
In plex I put
```
https://goplaxt.domain/api?id=XXXXXXXXX
```

After that nothing in any of the logs.

**Comment by EnorMOZ** [comment]
Not sure if this is the right way to test an actual webhook call to it but I ran this:
>curl --request POST \
  --url 'https://goplaxt.domain/api?id=XXXXXXXXXXX' \
  --form 'payload={
    "event": "media.scrobble",
    "user": true,
    "owner": true,
    "Account": {
        "id": 1,
        "thumb": "https://plex.tv/users/xxx/avatar?c=xxx",
        "title": "EnorMOZ"
    },
    "Server": {
        "title": "TVTime Fake Server",
        "uuid": "xxx"
    },
    "Player": {
        "local": true,
        "publicAddress": "172.17.0.1",
        "title": "Firefox",
        "uuid": "xxx"
    },
    "Metadata": {
        "librarySectionType": "show",
        "ratingKey": "83782",
        "key": "/library/metadata/83782",
        "parentRatingKey": "83764",
        "grandparentRatingKey": "83763",
        "guid": "com.plexapp.agents.thetvdb://76156/1/18?lang=en",
        "librarySectionTitle": "Series",
        "librarySectionID": 2,
        "librarySectionKey": "/library/sections/2",
        "type": "episode",
        "title": "Episode 18",
        "grandparentKey": "/library/metadata/83763",
        "parentKey": "/library/metadata/83764",
        "grandparentTitle": "Scrubs",
        "parentTitle": "Season 1",
        "contentRating": "TV-PG",
        "summary": "",
        "index": 1,
        "parentIndex": 1,
        "viewCount": 1,
        "lastViewedAt": 1537996938,
        "thumb": "/library/metadata/83782/thumb/1535581275",
        "art": "/library/metadata/83763/art/1535581275",
        "parentThumb": "/library/metadata/83764/thumb/1535581275",
        "grandparentThumb": "/library/metadata/83763/thumb/1535581275",
        "grandparentArt": "/library/metadata/83763/art/1535581275",
        "addedAt": 1535581221,
        "updatedAt": 1535581275
    }
}'

 and got the following:

>2018/12/19 16:28:58 Webhook call for XXXXXXXXXXX
2018/12/19 16:28:58 http: panic serving 172.18.0.9:45614: runtime error: index out of range
goroutine 22 [running]:
net/http.(*conn).serve.func1(0xc420430780)
	/usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0x75fa00, 0x9bff40)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/xanderstrike/goplaxt/lib/plex.HandleWebhook(0xc420364000, 0x6d0, 0xe00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/xanderstrike/goplaxt/lib/plex/main.go:13 +0x1b9
main.api(0x8108e0, 0xc42040cd20, 0xc420140700)
	/go/src/github.com/xanderstrike/goplaxt/main.go:68 +0x305
net/http.HandlerFunc.ServeHTTP(0x7e1348, 0x8108e0, 0xc42040cd20, 0xc420140700)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/xanderstrike/goplaxt/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420012240, 0x8108e0, 0xc42040cd20, 0xc420140700)
	/go/src/github.com/xanderstrike/goplaxt/vendor/github.com/gorilla/mux/mux.go:215 +0xed
net/http.serverHandler.ServeHTTP(0xc420098d00, 0x8108e0, 0xc42040cd20, 0xc420140400)
	/usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420430780, 0x810be0, 0xc4201ba5c0)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b

However I still don't see any normal plex calls to it

**Comment by XanderStrike** [comment]
If you're not seeing anything in the logs, and you know you're playing movies or tv shows, either Plex is set up wrong or your app isn't accessible on the _public internet_. 

If you turn off wifi on your phone, can you access your instance of Plaxt?

Have you tried re-doing the authentication and pasting the link into Plex?

**Comment by EnorMOZ** [comment]
App is public and tried reauth many times.

Sent from a mobile device.

________________________________

**Comment by EnorMOZ** [comment]
Well I feel stupid now.... It would actually help if webhooks was turned on in plex  🤦‍♂️

**Comment by crlshn** [comment]
I found on the console (plex/settings) some logs regarding the selftsigned certificate, remove https and re-deploy with http and works out of the box with the instructions provided
