### ISSUE TITLE
Managed users

### ISSUE THREAD

**Issue by brimur** [XanderStrike/goplaxt#51]
Hi, not an Issue as such but more of an FYI. I saw in your Readme you said you would no longer be working on this because Plex supports webhooks. Plex does but only for the primary user, ie the admin. My admin user has a PIN and is never used to watch stuff. I have a managed user called Watch that is used by everyone in my house to watch stuff. The Plex Webhook for Trakt does not support this so it is no use to me so just wanted to mention that 3rd part apps are still needed. Thanks for all your work.

**Comment by XanderStrike** [comment]
That's a great point! You're right it looks like Trakt doesn't support username filtering like this service does, so I'm glad to be filling in a void there. Despite not actively working on Plaxt much lately my hosted copy is still happily passing along 1000s of events daily and I'm certainly not planning on taking it down any time soon 😄 

Thank you for your appreciation!
