### ISSUE TITLE
Finding movies with mismatched release year

### ISSUE THREAD

**Issue by geaston95** [XanderStrike/goplaxt#58]
Currently, plaxt matches and finds movies based on title & release year. While effective most of the time, sometimes Plex metadata and Trakt release year do not match which results in Plaxt not correctly mapping the correct movie.

For example, the recently released 'A Quiet Place Part II' is listed as a 2020 film in Plex (using new Plex scanner), whereas Trakt lists it as 2021. This results in Plaxt not matching the movie and the scrobbling for that specific movie is never triggered. Could the plugin be updated to match using the imdb or tmdb unique ID's that Plex sends in the Webhook payload, similarly to how it currently handles TV episodes using the new Plex Scanner?

I would try and contribute, but i'm afraid i lack the technical knowledge to do so.

**Comment by XanderStrike** [comment]
This sounds like a great idea for a change. I would happily review and accept novice-level PRs for it if you or anyone else feels up to the challenge 😄
