### ISSUE TITLE
Send “Collected” info with Play

### ISSUE THREAD

**Issue by dannyvfilms** [XanderStrike/goplaxt#6]
Trakt has an option to mark a movie as part of your personal collection, as opposed to just having seen it somewhere. Presumably so people can keep track of what they own and what they still want to pick up.

Infuse for Apple TV seems to mark some collected TV episodes, but not movies. I’m not looking for anything retroactive, but if it’s possuble to send “collected” along with a play it would be handy.

**Comment by RcNorth** [comment]
Does the Plex API notify when it adds a new item to the collection?  If so, could this be used to update the Trakt collected when Plex adds a new item, vs waiting for it to be watched?

**Comment by dannyvfilms** [comment]
I really hope someone smarter than me has the answer to that one 😅

**Comment by XanderStrike** [comment]
This totally sounds doable, I can add it as a url parameter so you don't need to regenerate your URLs. I'll look into this later tonight.

The [Plex Webhooks](https://support.plex.tv/articles/115002267687-webhooks/) only get sent on play/pause/stop events, so we can't keep track of your unplayed items unfortunately.

**Comment by dannyvfilms** [comment]
Bump

**Comment by cgacord** [comment]
Based on Plex's webhooks page there is this option:

library.new – A new item is added to a library to which the user has access. A poster is also attached to this event.

Should be perfect for the collection of new items

**Comment by geogolem** [comment]
library.new would be good for marking collection of new items, but there is nothing I can see that could handle when items are removed from the PLEX collection.. i.e. they can be added via webhook, but not removed ... (as far as I can tell)..
