### ISSUE TITLE
Add option to load secrets from file

### ISSUE THREAD

**Issue by lumaxis** [XanderStrike/goplaxt#64]
I'd like to use [Docker secrets](https://docs.docker.com/engine/swarm/secrets) to manage my Trakt API app's ID and secret because I keep my `docker-compose.yml` file checked into git and obviously don't want to commit those secrets 😄 

Would be great if `goplaxt` could offer a way to load these from file, e.g. by allowing to use alternative `TRAKT_ID_FILE` and `TRAKT_SECRET_FILE` env vars that contain the path to the file containing the secret.

**Comment by jostyee** [comment]
You may store them into .env file: https://docs.docker.com/compose/environment-variables/#the-env-file
