### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by ryadre** [XanderStrike/goplaxt#68]
Hi, I see you are no longer working on this project which is a shame. Just thought I would make you aware it has stopped working in the past few days.
Thanks anyway for Plaxt! is has been amazing and I would continue to use it if it was still working.

Cheers

**Comment by abjugard** [comment]
Could you be a little more specific?

**Comment by ryadre** [comment]
> Could you be a little more specific?

Scrobbling has stopped working. Tried readding a new Web hook with a new link from Plaxt but it still doesn't scrobble to trakt.tv

**Comment by abjugard** [comment]
Wow, that's indeed a "little" more specific. I was hoping for something like a trace or error or anything more than just "not working".

**Comment by ryadre** [comment]
Oh OK sorry, I'm not sure how to do that or where to get any error codes from. I have just used https://plaxt.astandke.com/ website to get a web hook link for the past year, but now  the scrobble no longer works in Trakt for whatever reason, didn't think I would be the only person still using it and thought it may be a known issue. I can just use kodi with plex for now as the trakt scrobbling is still working with that. Cheers

**Comment by ryadre** [comment]
I just tried playing something in plex again and checked trakt and it is now working (without me doing anything), so whatever was happening has been resolved. Thanks
