### ISSUE TITLE
plax not working anymore

### ISSUE THREAD

**Issue by Arturoe1** [XanderStrike/goplaxt#69]
plax has stopped working, neither the selfhosted or the version in  https://plaxt.astandke.com/ seems to be working anymore .
i do belive this could be an outage of the trak api but it would be good if the app could handle this errors nicely

log in docker
2022/12/18 20:44:02 Got a 503 Service Unavailable error while refreshing :(
2022/12/18 20:44:02 http: panic serving 192.168.1.151:59326: interface conversion: interface {} is nil, not string
goroutine 87 [running]:
net/http.(*conn).serve.func1(0xc000400820)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x864340, 0xc000178bd0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
main.authorize(0x985ea0, 0xc00034c540, 0xc000100700)
	/go/src/github.com/xanderstrike/goplaxt/main.go:58 +0x7fe
net/http.HandlerFunc.ServeHTTP(0x901c20, 0x985ea0, 0xc00034c540, 0xc000100700)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/gorilla/handlers.ProxyHeaders.func1(0x985ea0, 0xc00034c540, 0xc000100700)
	/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/proxy_headers.go:59 +0x10d
net/http.HandlerFunc.ServeHTTP(0xc00047e1e0, 0x985ea0, 0xc00034c540, 0xc000100700)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000bc0c0, 0x985ea0, 0xc00034c540, 0xc000306000)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xe3
net/http.serverHandler.ServeHTTP(0xc000088b60, 0x985ea0, 0xc00034c540, 0xc000306000)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000400820, 0x9869e0, 0xc000058100)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4

**Comment by sasagr** [comment]
did u manage to fix? Still today, after Traktv is back, I getting an error. I reauthorized Trakt again, got a new webhook url but still no way to make it work

**Comment by sasagr** [comment]
[Req#62d0] Webhook: Error delivering payload to http://192.168.x.xx:8000/api?id=7b8f304eee978b675a0287xxxxxxx 404

**Comment by sasagr** [comment]
It started to work again (on its own), at least with the self-hosted

**Comment by ryadre** [comment]
Still not working here, went down when trakt was down, but hasn't seemed to work again unfortunately

**Comment by WebBuddha** [comment]
I've created an new Api and set the URL as the webhook. Works again.
